language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
sudo: required
services:
- docker
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y ansible
script:
- >
  wget -qO- bit.ly/ansibletest | env
  ANSIBLE_VERSIONS="1.4.4 1.5.4 1.9.2 2.1.0.0"
  DOCKER_IMAGES="ubuntu:12.04 ubuntu:14.04 ubuntu:16.04 fedora:21
  fedora:22 fedora:23"
  sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: kkI9ft4eU08T4g3J1Jh9NNsTloWIHhRftGBDRylH0s+ta8duf7Gl2bqSe10/H67s27HuLK1Hpr+mlNPKDBU6r7qipi+XrAn866lpdaVSye0fSrwKV/YtqbK1SVexsF81FVa6dHaxcIwwMMBPG+wmkBy/s4GBpkKA23PQKIMcQoH6/g79eGsNWBdOOATXJIaLxN/Qo918+oWyK6xSQTVoykQ5ChCP9BnNY2ggLKh33yiZS3L3uZ8en5Z5yJ7PRVeeYzHHDbT7XgPTItnETqVe8AsWUmxfLgVTUzEqchlIkvO7g8kZRVOr5y2bBIcRlce3z5JwKbB3eiE4Laf6RSoHNZNfi6rP1frke/1hrD13I/e4iSUljoGbKS7Vx80Lr426qf3DzeCkZdMRv+z4fDnUo2YODtHXtjE6YQpuUTA5Hqigzj7a0bZpLYR2EFHnTrRXaNUl0Juk0/fOxjDwJxyAn37tB8XSt9uusQDm93B3ttta/L8Ii6FuxlVqTWSDyz3QKGmJH2c9iiw25axfsgqxMCkx7awXGXXmVKWE0dqh8gua4hJwtlJ3zuDEjAlvgMmeTZMfv5jx679uqxHaFrBegAWpN0EirxJmo11KLCRzh3fmvuziTlrii63O0DVTb0N4x8piSgNkoLFK8NLFxOfxiM5mkMSgWHWB4NU/n9G5Xg4=
  email:
    recipients:
      secure: ks9pKHxU6yJI3d804s+fcNoDQ+4RQXEY4VUcYq044M4FtkxohoDIZCG7dmXhwXdYI3RTWt9HBw0/il0Me//AZLLlOZFpINLYeFzo+zd4oukSi0TyL1gnp6VOAhEf+DrOOHCJf0v+rZqtzkRtGrqSgzoo5hUSHrZ38Ec4P9X+/ePHK5hhtVU4H46ccBn77pHLjI5xaEhuCBe1sjwi2DMJyKJZ0rFIHQWPeQQwGLVWB5xTR4EPQC1Dv76gVIiTpH9w5h2T523ulty+O/nk3bqQ2L/NWtts1431DOPzbAQff3432HrBL7kaNJrQD3Ek1XkWHPM3AU+WKWkGNLEZ5SNzCXh2eetFLR8UIe0GfZ3pCorvDLNwFKuDJTE2Hmk40Q+44EvI4mv61NLClylylWcAG/VAsR4dI79915riToKQkL+s3++qSJMRgA+7utyoztbSBYaYIccEItWEZW4qqS76V2FlirF38SK35uKJb2Q0giv7ZiUOjomA9grVqZOzvj6vDUQdTvU4OwmwSSIXzaF51VfQh/xw09lsHGiQ8xnK2+X9n36UW2lIyH54ACzb5Tbub2xMQ8kecOCRsFHnFYIrBugb03TjfQW2mQDcwZ3Jtwnm0tsrSQs07UG1HXXOljwJMG7JuxmPIFe3KmjLqLHxlNQayB0gZEfoyjIMI1lvonQ=
